allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  prisma: true
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
overrides:
  deepmerge-ts: 8.0.0
  'fast-uri@>=3.0.0 <4.0.0': 3.1.7
  'fast-uri@>=4.0.0 <5.0.0': 4.1.4
  mysql2: 3.23.1
